---
kind: NgrokModuleSet
apiVersion: ingress.k8s.ngrok.com/v1alpha1
metadata:
  name: faces-demo
  namespace: faces
modules:
  compression:
    enabled: true
  tlsTermination:
    minVersion: "1.3"
  oauth:
    google:
      emailDomains:
      - ngrok.com
  circuitBreaker:
    errorThresholdPercentage: "0.50"
    trippedDuration: 10s
    rollingWindow: 60s
    numBuckets: 10
    volumeThreshold: 20
